### ISSUE TITLE
Better auto-partitioning during image loading

### ISSUE THREAD

**Issue by freeman-lab** [thunder-project/thunder#111]
Now that image loading supports an optional argument for the number of partitions, we should set the default in a smarter way. Rather than the default being one partition per image, it should probably be related to the number of workers, as given by `sc.defaultParallelism`.

For some operations there can be dramatic performance decrements when over-partitioning. For example, when loading these image data and computing a mean:

```
path = 's3n://neuro.datasets/svoboda.lab/tactile.navigation/1/'
data = tsc.loadImages(path + 'images-binary', recursive=True, dims=[512,512,4], ext='bin')
img = data.mean()
```

takes several minutes with `npartitions` set to the default (the number of images, in this case 9000). but only a few seconds with `npartitions=50`. 

Doing some testing with @Andrewosh, we found that the optimal number of partitions for this particular reduce operation and data is around half the number of executors. However, for other workflows (e.g. primarily with map operations) the level of parallelism should be set to 2-3x the number of executors. This difference, we think, is due to the fact that for images the records are particularly large, increasing the strain on data communication and serializion during the reduce.

Our proposal is to set the default `npartitions=sc.defaultParallelism` during image loading, which strikes a balance between these concerns. 

@industrial-sloth ?

**Comment by industrial-sloth** [comment]
I'd be curious what the comparison was like reading from something other than s3 - though this probably doesn't account for a majority of the performance difference, see below. With s3, a new connection is opened for each partition; setting the number of partitions to be less than the number of files allows these to be reused. So there's some overhead being saved right there, though this probably doesn't account for the difference of minutes down to seconds. 

I also have previously seen some pretty dramatic performance improvements from `coalesce()`ing before calculating a mean. The mean is first calculated locally within partitions before shuffling, and so the total amount of data being pushed across the network drops by a factor of the number of images included in a partition. I think then this might just happen to be a worst-case scenario for overpartitioning, rather than being generally representative,

The big concern with underpartitioning, in contrast, is what happens when the size of a single partition exceeds the available memory on a worker - I don't know, but I suspect bad things. (As I recall, it was a desire to be conservative here that led to the initial one-partition-per-image setup.) Let's say we have 150MB images and 4G available memory. We probably want to avoid going over 2G in any single partition, since Java increases buffer size by factors of 2 and so anything over 2G may run a risk of accidentally turning into a 4G allocation. This gives us a target of maybe 12 or so images per partition. Looks like in standalone mode `default.parallelism` defaults (ahem) to the number of cores in the cluster: http://spark.apache.org/docs/1.2.0/configuration.html. So for 1000 images we'd want 80-something cores in order to feel reasonably safe? This sounds like in the ballpark of what I'd expect as reasonable, and so I think I'm probably okay with the `default.parallelism` proposal. 

Probably worth testing this first though. :)

**Comment by freeman-lab** [comment]
Thanks @industrial-sloth great thoughts. This was actually on the Janelia cluster (forgot to mention), probably worth testing on S3 as well.

I forgot the concern about keeping the max size / partition down, definitely another dimension to consider. Perhaps, then, we need to do an upfront calculation of the size of each record (based on dimensions). The problem I see is that we don't know how to get the size of each record for `tif`, only for `binary`. But assuming we had it (hrm)... we could basically pick a number of partitions that was either (a) the `defaultParallelism` or (b) number of partitions such that the total expected data set size divided by the number of partitions was less than or equal to some bound (say 2GB), and pick whichever is larger?

Your experience with `coalesce` is exactly in line with the observations here, the thought was to try and do that for the user up front, at least to some extent, by using at least fewer than the number of images, which for moderate size images especially becomes enormous.

This all started because a user basically called `Images.mean()` as the first operation and couldn't get it to finish / maybe crashed the cluster. Fairly natural thing to do, and definitely not a great first impression =)

**Comment by freeman-lab** [comment]
Fixed in https://github.com/thunder-project/thunder/commit/28ba172660f817fa77fe7c64c2f51204773dc469
