### ISSUE TITLE
Thunder 1.0.0 reduce() error

### ISSUE THREAD

**Issue by boazmohar** [thunder-project/thunder#248]
While I am not sure this is the correct syntax, I would expect reduce in thunder with bolt to work on values only so this should work:
```python
import numpy as np
data = thunder.images.fromrandom(engine=sc)
result = data.reduce(np.mean)
# or this
result = data.reduce(lambda x: np.nanmean(x, axis=0))
```
I get errors indicating that a key value pair was passed:
```
File "/usr/local/python-2.7.6/lib/python2.7/site-packages/numpy/core/_methods.py", line 50, in _count_reduce_items
    items *= arr.shape[ax]
TypeError: only integer arrays with one element can be converted to an index
```
As a check this works:
```python
result = data.tordd().reduce(lambda k, v: np.nanmean(v, axis=0))
result.shape
# out: (50, 50)
```

Is this the correct use for reduce with bolt?

**Comment by jwittenbach** [comment]
@boazmohar The issue here is that `reduce` needs a *binary* operator as the function that you pass it. For example, the following works:

```
import numpy as np
data = thunder.images.fromrandom(engine=sc)
result = data.reduce(lambda x, y: x+y)
# or this
result = data.reduce(lambda x: np.nanmean(x, axis=0))
```

The problem with using `np.mean` is that this function operates on a single array, not two arrays. Also, if you want to use a `reduce` to compute the mean of a dataset, you have to be careful -- iteratively taking pair-wise means across a set of values does not end up being the same thing as computing the mean of that same set of values.

**Comment by boazmohar** [comment]
Thanks, I will change my code!
On another note... can you verify that we have a missing numpy function...
I don't know how but there is no ```numpy.stack()``` it should be in

/usr/local/python-2.7.6/lib/python2.7/site-packages/numpy/core/shape_base.py 
 
like here:
https://github.com/numpy/numpy/blob/master/numpy/core/shape_base.py

sorry to change the subject but I want to know I haven't lost my mind

**Comment by freeman-lab** [comment]
@boazmohar I think that's from a different version of `numpy` than the one you are running, note that the link you posted to is from `master`. I'll close this issue for now, but we can discuss the `numpy` thing offline =)
