### ISSUE TITLE
Example fish data

### ISSUE THREAD

**Issue by laserson** [thunder-project/thunder#370]
There used to be an example data set which was the 76 x 87 x 2 fish data for 240 time points.  Is this still available?  I am updating Advanced Analytics with Spark and can't find it hosted anywhere convenient.

**Comment by jwittenbach** [comment]
The example data is still available, it's just now hosted externally to the code base. In Thunder 1.0, you can import it with:
```python
import thunder as td
data = td.images.fromexample('fish')
```
If you look in the code, you can see where it's hosted if you'd rather just pull the raw data:
https://github.com/thunder-project/thunder/blob/master/thunder/images/readers.py#L485

**Comment by laserson** [comment]
AFAICT that's a different data set from
https://github.com/thunder-project/thunder/tree/v0.4.1/python/thunder/utils/data/fish/bin

**Comment by jwittenbach** [comment]
I think the datasets are the same with two minor differences:
1. I was loading it as `Images` instead of `Series`
```python
import thunder as td
data = td.series.fromexample('fish')
```
When I run that, it comes out as the same size as the old data -- (76, 87, 2, 20) for (x, y, z, t)

2. We changed our on-disk binary format for `Series` data between Thunder 0.6 and 1.0. So you're correct that the files are different. However, once loaded into memory, I think they should be identical.

**Comment by laserson** [comment]
The data set I pointed to is sized `(76, 87, 2, 240)`.  Note: **240** time points rather than 20.

**Comment by jwittenbach** [comment]
Ah interesting, I didn't know we had downsized (haven't played with the old version in a long time). In that case, the data in the archived version of Thunder that you pointed to are the only public copies of it that I know of.

**Comment by laserson** [comment]
k, sounds good.
